name: Test Coverage

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: cortex_pass
          POSTGRES_USER: cortex_user
          POSTGRES_DB: cortex_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 5432:5432

    env:
      POSTGRES_HOST: postgres
      POSTGRES_USER: cortex_user
      POSTGRES_PASSWORD: cortex_pass
      POSTGRES_DB: cortex_db
      POSTGRES_PORT: 5432
      JWT_SECRET: test-secret-key-for-testing
      REFRESH_SECRET: test-refresh-secret-for-testing
      TEST_DB_MODE: ci

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: go mod download

    - name: Install PostgreSQL client
      run: sudo apt-get update && sudo apt-get install -y postgresql-client

    - name: Wait for PostgreSQL
      run: |
        echo "Waiting for PostgreSQL to be ready..."
        timeout=60
        elapsed=0
        until psql -h postgres -U cortex_user -d cortex_db -c "SELECT 1;" >/dev/null 2>&1; do
          sleep 2
          elapsed=$((elapsed + 2))
          if [ $elapsed -ge $timeout ]; then
            echo "Timeout waiting for PostgreSQL after ${timeout} seconds"
            exit 1
          fi
        done
        echo "✅ PostgreSQL is ready and accepting connections!"

    - name: Run tests with coverage
      run: go test -v ./... -coverprofile=coverage.out

    - name: Generate coverage report
      run: go tool cover -html=coverage.out -o coverage.html

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Archive coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.html
